.PHONY : all debug release backup
.SUFFIXES : .cpp .o

SOURCES  := $(wildcard *.cpp)
INCLUDES := 
OBJECTS  := $(SOURCES:.cpp=.o)
LIBRARY := -lpthread
CPP := g++
TARGET = test

all : DEBUG

$(TARGET) : $(OBJECTS)
	$(CPP) -o $@  $^ 

.cpp.o : $(SOURCES)
	$(CPP) $(SOURCES) $(CPPFLAGS) $(INCLUDES) $(LIBRARY)

clean :
	rm -rf $(OBJECTS) $(TARGET) *~

DEBUG : CPPFLAGS := -g -c -Wall -Werror -std=c++0x -fopenmp 
DEBUG : $(TARGET)

RELEASE : CPPFLAGS := -O0 -c -Wall -Werror -std=c++0x -fopenmp 
RELEASE : $(TARGET)
